services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: event_store
      POSTGRES_USER: event_store_user
      POSTGRES_PASSWORD: event_store_password
    ports:
      - 5432:5432